[package]
name = "PKU-UThesis"
version = "0.0.1"
entrypoint = "src/lib.typ"
authors = ["sjfhsjfh"]
description = "Template for PKU thesis. U for undergraduate."
keywords = [
    "undergraduate",
    "PKU",
    "thesis",
    "template",
]
categories = ["thesis"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "template/thesis.typ"

[tool]
